export const interestData = [
  {
    name: 'Python',
    tags: [
      '爬虫开发',
      '数据分析',
      '机器学习',
      '深度学习',
      '自动化脚本',
      'Flask',
      'Django',
      'FastAPI',
      'Web开发',
      '科学计算',
      '协程',
    ],
  },
  {
    name: 'Java',
    tags: [
      'SpringBoot',
      'Spring Cloud',
      'MyBatis',
      'JVM',
      '微服务',
      'Java Web',
      'JUC 并发',
      'Netty',
      '设计模式',
    ],
  },
  {
    name: '编程语言',
    tags: [
      'C',
      'C++',
      'Go',
      'Rust',
      'JavaScript',
      'TypeScript',
      'Kotlin',
      'PHP',
      'Swift',
      'Dart',
      'R',
      'Shell',
      'SQL',
    ],
  },
  {
    name: '开发工具',
    tags: [
      'Git',
      'VS Code',
      'IDEA',
      'Docker',
      'Postman',
      'Jenkins',
      'Kubernetes',
      'Nginx',
      'GitHub',
      'GitLab',
    ],
  },
  {
    name: '数据结构与算法',
    tags: [
      '链表',
      '树',
      '二叉树',
      '图',
      '动态规划',
      '贪心',
      '排序算法',
      '回溯',
      '堆',
      '栈',
      '队列',
    ],
  },
  {
    name: '大数据',
    tags: [
      'Hadoop',
      'Spark',
      'Flink',
      'Hive',
      'HBase',
      'Kafka',
      '数据仓库',
      '数仓建模',
    ],
  },
  {
    name: '前端',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Vue',
      'React',
      'Next.js',
      'TailwindCSS',
      '小程序',
      'Vite',
      '前端工程化',
    ],
  },
  {
    name: '后端',
    tags: [
      'RESTful API',
      'JWT 鉴权',
      '微服务',
      'RPC',
      '分布式',
      '数据库设计',
      '消息队列',
      'API 网关',
    ],
  },
  {
    name: '云原生',
    tags: [
      'Docker',
      'Kubernetes',
      'Istio',
      'Helm',
      'Prometheus',
      'Grafana',
      'Serverless',
      'DevOps',
    ],
  },
  {
    name: '移动开发',
    tags: [
      'Android',
      'iOS',
      'Flutter',
      'React Native',
      'Kotlin',
      '移动端适配',
      '性能优化',
    ],
  },
  {
    name: '人工智能',
    tags: [
      '深度学习',
      '机器学习',
      'NLP',
      'CV',
      'Transformer',
      'AI 应用开发',
      '语音识别',
      '大模型',
    ],
  },
  {
    name: '网络与通信',
    tags: ['TCP/IP', 'HTTP', 'HTTPS', 'WebSocket', '网络抓包', 'DNS', 'VPN'],
  },
  {
    name: '嵌入式',
    tags: ['单片机', 'STM32', 'Arduino', '物联网', '嵌入式 Linux'],
  },
  {
    name: '硬件开发',
    tags: ['PCB 设计', '电路基础', '数字电路', 'FPGA', '传感器'],
  },
  {
    name: '游戏',
    tags: [
      'Unity',
      'Unreal（UE）',
      'Cocos',
      '游戏引擎',
      '游戏策划',
      '游戏建模',
    ],
  },
  {
    name: 'HarmonyOS',
    tags: ['ArkUI', '鸿蒙应用开发', '分布式能力', 'DevEco Studio'],
  },
  {
    name: '微软技术',
    tags: ['.NET', 'C#', 'Azure', 'WPF', 'Blazor'],
  },
  {
    name: '操作系统',
    tags: ['Linux', 'Windows 内核', '系统调优', 'Shell 编程', '文件系统'],
  },
  {
    name: '搜索',
    tags: ['Elasticsearch', '搜索引擎', '倒排索引', '搜索优化'],
  },
  {
    name: '设计模式',
    tags: [
      '工厂模式',
      '单例模式',
      '策略模式',
      '观察者模式',
      '装饰器模式',
      'MVC/MVVM',
    ],
  },
  {
    name: '测试',
    tags: [
      '单元测试',
      '接口测试',
      '自动化测试',
      '性能测试',
      'pytest',
      'JMeter',
    ],
  },
  {
    name: '云平台',
    tags: ['阿里云', '腾讯云', '华为云', 'AWS', 'GCP'],
  },
  {
    name: '软件工程',
    tags: ['架构设计', '敏捷开发', 'Scrum', 'CI/CD', '项目管理'],
  },
  {
    name: '区块链',
    tags: ['Web3', 'Solidity', '智能合约', '以太坊', '区块链安全'],
  },
  {
    name: '数学',
    tags: ['高等数学', '线性代数', '概率论', '统计学', '运筹学', '离散数学'],
  },
  {
    name: '运维',
    tags: ['Linux 运维', '自动化运维', '监控告警', '故障排查'],
  },
  {
    name: '网络空间安全',
    tags: ['渗透测试', '漏洞分析', 'CTF', '逆向工程', 'Web 安全', '加密算法'],
  },
  {
    name: '服务器',
    tags: ['Nginx', 'Apache', 'Redis', 'MySQL', 'PostgreSQL', 'MongoDB'],
  },
  {
    name: '学习和成长',
    tags: ['自律', '高效学习', '时间管理', '效率工具'],
  },
  {
    name: '教育培训',
    tags: ['在线课程', 'IT 培训', '技术分享', '考证'],
  },
  {
    name: '用户体验设计',
    tags: ['交互设计', 'UI 设计', '原型设计', '用户研究', '信息架构'],
  },
  {
    name: '音视频',
    tags: ['FFmpeg', 'WebRTC', '视频编码', '音频处理', '直播技术'],
  },
  {
    name: '行业数字化',
    tags: ['电商系统', '金融科技', '智慧城市', '物流系统', '医疗信息化'],
  },
  {
    name: '非 IT 技术',
    tags: ['心理学', '摄影', '绘画', '音乐', '健身'],
  },
  {
    name: '前沿技术',
    tags: ['AI Agent', '数字孪生', '边缘计算', 'VR/AR', '量子计算'],
  },
  {
    name: 'IT 工具',
    tags: ['ChatGPT', 'Copilot', 'Cursor', '飞书', 'Notion'],
  },
  {
    name: '开发组件',
    tags: ['UI 组件库', '工具类', '自定义 Hook', '封装组件'],
  },
  {
    name: '开源',
    tags: ['开源项目', '代码审查', 'GitHub 贡献', 'Issue/PR'],
  },
  {
    name: '其他',
    tags: ['科技新闻', '博客搭建', '个人网站', '效率提升'],
  },
  {
    name: '3C 硬件',
    tags: ['键盘', '鼠标', '显卡', '电脑 DIY', '主机搭建'],
  },
  {
    name: 'AIGC',
    tags: ['提示词工程', '图像生成', 'AI 编程', '模型微调', 'AI 创作'],
  },
]
