import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ThemeProvide'
import { Toaster } from '@/components/ui/sonner'
import HomeTopBar from '@/components/home/TopBar'
import PageTransition from '@/components/PageTransition'
import { SidebarProvider } from '@/components/ui/sidebar'
import { WSInitializer } from './ws-init-client'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f0eeee] dark:bg-[#0a0a0a] overflow-auto`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <WSInitializer />
          <HomeTopBar className="fixed top-0 left-0 w-full z-40" />
          <PageTransition />
          <SidebarProvider className="w-full">
            <div className="mt-18 max-w-[1400px] w-[1400px] mx-auto">
              {children}
            </div>
          </SidebarProvider>
          <Toaster position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  )
}
